title: Michael's website
email: michael.ruppe@live.com.au
description: > # this means to ignore newlines until next code part
  Code art and machine-learning projects by Michael Ruppe



show_excerpts: true # set to true to show excerpts on the homepage
lsi: true

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%-d %b, %Y"

  google_analytics: UA-28165457-1

  # generate social links in footer
  social_links:
    github: michaelruppe
    linkedin: michael-ruppe-0a3b12b9
    # rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # youtube: jekyll
    # youtube_channel:
    # youtube_channel_name:


collections:
  docs:
    output: true
    permalink: /docs/:name
  Creative:
    output: true
  MachineLearning:
    output: true
  MiscProjects:
    output: true



# What links to show in the header-bar
header_pages:
  - about.md
  - Creative.md
  - MachineLearning.md
  - MiscProjects.md

# Build settings
theme: minima

# Plugins
plugins:
  - jekyll-menus
