title: Michael's website
email: michael.ruppe@live.com.au
description: > # this means to ignore newlines until next code part
  Code art and machine-learning projects by Michael Ruppe



show_excerpts: true # set to true to show excerpts on the homepage
lsi: true

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  google_analytics: UA-28165457-1

  # generate social links in footer
  social_links:
    github: michaelruppe
    linkedin: michael-ruppe-0a3b12b9
    # rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

# Plugins
plugins:
  - jekyll-menus

# plugins_dir:
#  - jekyll-feed
#  - jekyll-seo-tag


# Global permalink template (date used for posts, ignored for pages)
# permalink: /:categories/:year/:month/:day/:title:output_ext
